#!/bin/bash
set -e
export PGPASSWORD=$POSTGRES_PASSWORD;
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER $TEST_DB_USER WITH PASSWORD '$TEST_DB_PASSWORD';
  CREATE DATABASE "$TEST_DB";
  GRANT ALL PRIVILEGES ON DATABASE "$TEST_DB" TO $TEST_DB_USER;
EOSQL